-- CreateTable
CREATE TABLE "site_settings" (
    "id" TEXT NOT NULL DEFAULT 'site_settings',
    "siteTitle" TEXT NOT NULL DEFAULT 'Loïc Ghanem | Music Composer & Producer',
    "siteDescription" TEXT NOT NULL DEFAULT 'Award-winning music composer and producer',
    "contactEmail" TEXT NOT NULL DEFAULT 'contact@loicghanem.com',
    "contactPhone" TEXT,
    "location" TEXT NOT NULL DEFAULT 'Paris, France',
    "footerBio" TEXT,
    "socialYoutube" TEXT,
    "socialInstagram" TEXT,
    "socialFacebook" TEXT,
    "socialTwitter" TEXT,
    "socialLinkedin" TEXT,
    "socialSoundcloud" TEXT,
    "socialSpotify" TEXT,
    "socialAppleMusic" TEXT,
    "socialBandcamp" TEXT,
    "socialTiktok" TEXT,
    "homepageFeaturedAlbumsCount" INTEGER NOT NULL DEFAULT 6,
    "homepageLatestVideosCount" INTEGER NOT NULL DEFAULT 6,
    "albumsPerPage" INTEGER NOT NULL DEFAULT 12,
    "videosPerPage" INTEGER NOT NULL DEFAULT 12,
    "servicesPerPage" INTEGER NOT NULL DEFAULT 10,
    "defaultAlbumSort" TEXT NOT NULL DEFAULT 'date_desc',
    "defaultVideoSort" TEXT NOT NULL DEFAULT 'date_desc',
    "homepageWelcomeMessage" TEXT,
    "showFeaturedAlbums" BOOLEAN NOT NULL DEFAULT true,
    "showLatestVideos" BOOLEAN NOT NULL DEFAULT true,
    "showServices" BOOLEAN NOT NULL DEFAULT true,
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "maintenanceMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "site_settings_pkey" PRIMARY KEY ("id")
);
